[package]
name = "many-migration"
version = "0.1.1" # managed by release.sh
edition = "2021"
description = "Storage/Transaction migration framework."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-error = { path = "../many-error", version = "0.1.1" } # managed by release.sh
minicbor = { version = "0.19.1", features = ["derive"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
strum = { version = "0.24.1", features = ["derive"] }
tracing = "0.1.37"

[dev-dependencies]
linkme = { version = "0.3.9", features = ["used_linker"] }
