[package]
name = "many-web"
version = "0.1.4" # managed by release.sh
edition = "2021"

[[bin]]
name = "many-web"
doc = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
clap = { version = "3.2.25", features = ["derive"] }
coset = "0.3.4"
hex = { version = "0.4.3", features = ["serde"] }
json5 = "0.4.1"
many-cli-helpers = { path = "../many-cli-helpers", version = "0.1.4" } # managed by release.sh
many-error = { path = "../many-error", version = "0.1.4" } # managed by release.sh
many-identity = { path = "../many-identity", features = ["default", "serde"], version = "0.1.4" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ed25519", "ecdsa"], version = "0.1.4" } # managed by release.sh
many-identity-webauthn = { path = "../many-identity-webauthn", version = "0.1.4" } # managed by release.sh
many-modules = { path = "../many-modules", version = "0.1.4" } # managed by release.sh
many-protocol = { path = "../many-protocol", version = "0.1.4" } # managed by release.sh
many-server = { path = "../many-server", version = "0.1.4" } # managed by release.sh
many-server-cache = { path = "../many-server-cache", version = "0.1.4" } # managed by release.sh
many-types = { path = "../many-types", version = "0.1.4" } # managed by release.sh
merk = { git = "https://github.com/liftedinit/merk.git", rev = "532eb097ec50f3553c5294971c152b4e7c7d4731" }
minicbor = { version = "0.19.1", features = ["derive", "std"] }
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
signal-hook = "0.3.15"
tempfile = "3"
tokio = { version = "1.28.1", features = [ "full" ] }
tracing = "0.1.37"

[build-dependencies]
vergen = { version = "8.2.1", features = ["git", "git2"] }
