[package]
name = "many-kvstore"
version = "0.1.3" # managed by release.sh
edition = "2021"
description = "MANY kvstore server."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]
build = "build.rs"

[[bin]]
name = "many-kvstore"
doc = false

[dependencies]
async-trait = "0.1.68"
clap = { version = "3.2.25", features = ["derive"] }
coset = "0.3.4"
merk = { git = "https://github.com/liftedinit/merk.git", rev = "532eb097ec50f3553c5294971c152b4e7c7d4731" }
hex = { version = "0.4.3", features = ["serde"] }
json5 = "0.4.1"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
minicbor = { version = "0.19.1", features = ["derive", "std"] }
many-cli-helpers = { path = "../many-cli-helpers", version = "0.1.3" } # managed by release.sh
many-error = { path = "../many-error", version = "0.1.3" } # managed by release.sh
many-identity = { path = "../many-identity", features = ["default", "serde"], version = "0.1.3" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ed25519", "ecdsa"], version = "0.1.3" } # managed by release.sh
many-identity-webauthn = { path = "../many-identity-webauthn", version = "0.1.3" } # managed by release.sh
many-modules = { path = "../many-modules", version = "0.1.3" } # managed by release.sh
many-protocol = { path = "../many-protocol", version = "0.1.3" } # managed by release.sh
many-server = { path = "../many-server", version = "0.1.3" } # managed by release.sh
many-server-cache = { path = "../many-server-cache", version = "0.1.3" } # managed by release.sh
many-types = { path = "../many-types", version = "0.1.3" } # managed by release.sh
serde = "1.0.163"
sha3 = "0.10.8"
signal-hook = "0.3.15"
strum = "0.24.1"
tokio = { version = "1.28.1", features = [ "full" ] }
tracing = "0.1.37"

[dev-dependencies]
async-channel = "1.8.0"
once_cell = "1.17.1"
many-identity = { path = "../many-identity", features = ["default", "serde", "testing"], version = "0.1.3" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = [ "ed25519", "testing" ], version = "0.1.3" } # managed by release.sh
tempfile = "3.5.0"

[build-dependencies]
vergen = { version = "8.2.1", features = ["git", "git2"] }
