[package]
name = "many-kvstore"
edition = "2021"
readme = "README.md"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "liftedinit"]
categories = ["command-line-utilities"]
version = "0.1.1" # managed by release.sh
description = "MANY kvstore server."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]
build = "build.rs"

[[bin]]
name = "many-kvstore"
doc = false

[dependencies]
async-trait = "0.1.51"
clap = { version = "3.0.0", features = ["derive"] }
coset = "0.3"
derive_more = "0.99"
hex = { version = "0.4.3", features = ["serde"] }
json5 = "0.4.1"
lazy_static = "1.4.0"
merk_v1 = { package = "merk", git = "https://github.com/liftedinit/merk.git", rev = "857bf81963d9282ab03438da5013e1f816bd9da1" }
merk_v2 = { package = "merk", git = "https://github.com/MavenRain/merk.git", branch = "merk-hash-migration" }
minicbor = { version = "0.18.0", features = ["derive", "std"] }
num-bigint = "0.4.3"
many-cli-helpers = { path = "../many-cli-helpers", version = "0.1.1" } # managed by release.sh
many-error = { path = "../many-error", version = "0.1.1" } # managed by release.sh
many-identity = { path = "../many-identity", features = ["default", "serde"], version = "0.1.1" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ed25519", "ecdsa"], version = "0.1.1" } # managed by release.sh
many-modules = { path = "../many-modules", version = "0.1.1" } # managed by release.sh
many-protocol = { path = "../many-protocol", version = "0.1.1" } # managed by release.sh
many-server = { path = "../many-server", version = "0.1.1" } # managed by release.sh
many-types = { path = "../many-types", version = "0.1.1" } # managed by release.sh
serde = "1.0.130"
sha3 = "0.10.4"
signal-hook = "0.3.13"
strum = "0.24.1"
tokio = { version = "1.24.1", features = [ "full" ] }
tracing = "0.1.28"

[dev-dependencies]
async-channel = "1.8"
once_cell = "1.14.0"
many-identity = { path = "../many-identity", features = ["default", "serde", "testing"], version = "0.1.1" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = [ "ed25519", "testing" ], version = "0.1.1" } # managed by release.sh
tempfile = "3.3.0"

[build-dependencies]
vergen = "7"
