name: CI
on:
  - push
  - pull_request
jobs:
  build_and_test:
    name: many-rs build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SoftHSMv2
        run: |
          sudo apt-get update -y -qq &&
          sudo apt-get install -y -qq libsofthsm2 &&
          mkdir /tmp/tokens
          echo "directories.tokendir = /tmp/tokens" > /tmp/softhsm2.conf
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt, llvm-tools-preview
      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --all-targets --all-features -- -D warnings
      - name: Install grcov
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov --root target/
      - name: Perform build (--release)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
          SOFTHSM2_CONF: /tmp/softhsm2.conf
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "coverage/lcov-%p-%m.profraw"
        with:
          command: test
          args: --all-targets --all-features
      - name: grcov
        shell: bash
        run: |
          ./target/bin/grcov src --binary-path target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./coverage/report.lcov
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/report.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: code-coverage-report
      - name: Code Coverage Report (romeovs)
        uses: romeovs/lcov-reporter-action@v0.2.19
        with:
          lcov-file: ./coverage/report.lcov
          title: Code Coverage Report
          filter-changed-files: true
          delete-old-comments: true
